modLoader = "javafml"
loaderVersion = "[36,)"
license = "MIT"

[[mods]]
modId = "fpsdisplayer"
version = "1.0.0"
displayName = "ยง6ยงlJustยงeยงlProject ยงfยงlFPS Display"
description = """ยง6โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ
ยง6โ    ยงeยงlJUSTPROJECT FPS DISPLAYER    
ยง6โโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโโ

ยงaโ ยงfAdvanced FPS display mod ยงaโ

ยงbโก ยง6FEATURES:
ยง7โข ยงfFPS, CPS, Coordinates
ยง7โข ยงfArmor durability  
ยง7โข ยงfEntity info
ยง7โข ยงfKey bind system

ยงe๐ฎ ยง6COMMANDS:
ยง7โขยงe .bind ยงf- Create key binds
ยง7โขยงe .binds ยงf- List binds
ยง7โขยงe .unbind ยงf- Remove binds

ยงcโค ยง6BY: ยงfJustProject Team"""
authors = "JustProject Team"
logoFile = "justproject_logo.png"
displayURL = "https://github.com/JustProjectMods/FPS-displayer"
issuesURL = "https://github.com/JustProjectMods/FPS-displayer/issues"
updateJSONURL = "https://raw.githubusercontent.com/JustProjectMods/FPS-displayer/main/update.json"

[["dependencies.fpsdisplayer"]]
modId = "forge"
versionRange = "[36.2.42,)"
ordering = "NONE"
mandatory = true
side = "CLIENT"

[["dependencies.fpsdisplayer"]]
modId = "minecraft"
versionRange = "[1.16.5,)"
ordering = "NONE"
mandatory = true
side = "CLIENT"
